//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyectofinal2.Models.Menajes_db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carrito
    {
        public int Id_carrito { get; set; }
        public Nullable<int> Valor_neto { get; set; }
        public Nullable<int> Descuento { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<int> Subtotal { get; set; }
    }
}
