//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyectofinal2.Models.Menajes_db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categoria
    {
        public Categoria()
        {
            this.Subcategoria = new HashSet<Subcategoria>();
        }
    
        public int Id_categoria { get; set; }
        public string Nombre_categoria { get; set; }
        public string Tipo { get; set; }
        public Nullable<int> Cantidad { get; set; }
    
        public virtual ICollection<Subcategoria> Subcategoria { get; set; }
    }
}
