//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyectofinal2.Models.Menajes_db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Debito
    {
        public Debito()
        {
            this.Metodo_pago = new HashSet<Metodo_pago>();
        }
    
        public int Cod_deposito { get; set; }
        public string Num_cuenta { get; set; }
    
        public virtual Banco_menaje Banco_menaje { get; set; }
        public virtual ICollection<Metodo_pago> Metodo_pago { get; set; }
    }
}
