//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyectofinal2.Models.Menajes_db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Direccion
    {
        public int Id_direccion { get; set; }
        public string Calle { get; set; }
        public Nullable<int> Numero { get; set; }
        public string Comuna { get; set; }
        public string Ciudad { get; set; }
        public string Cod_postal { get; set; }
        public Nullable<int> Num_departamento { get; set; }
    }
}
