//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyectofinal2.Models.Menajes_db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresa_cliente
    {
        public Empresa_cliente()
        {
            this.Usuarios = new HashSet<Usuarios>();
        }
    
        public string Id_empresacliente { get; set; }
        public string Giro { get; set; }
        public string Contacto_empresa { get; set; }
    
        public virtual ICollection<Usuarios> Usuarios { get; set; }
    }
}
