//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyectofinal2.Models.Menajes_db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mensaje_consulta
    {
        public int Id_contacto { get; set; }
        public string Motivo { get; set; }
        public string Estado { get; set; }
        public string Mensaje { get; set; }
    }
}
