//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyectofinal2.Models.Menajes_db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Metodo_pago
    {
        public int Id_metodo_pago { get; set; }
        public string Nombre { get; set; }
        public string Tipo { get; set; }
        public Nullable<int> Id_carrito { get; set; }
        public Nullable<int> Cod_deposito { get; set; }
    
        public virtual Carrito Carrito { get; set; }
        public virtual Debito Debito { get; set; }
    }
}
