//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyectofinal2.Models.Menajes_db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subcategoria
    {
        public Subcategoria()
        {
            this.Producto = new HashSet<Producto>();
        }
    
        public int Id_subcategoria { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Id_categoria { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        public virtual ICollection<Producto> Producto { get; set; }
    }
}
