//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyectofinal2.Models.Menajes_db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public Usuarios()
        {
            this.Mensaje_consulta = new HashSet<Mensaje_consulta>();
            this.Ventas = new HashSet<Ventas>();
        }
    
        public string Rut { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Email { get; set; }
        public string Telefono { get; set; }
        public string Usuario { get; set; }
        public string Contrasena { get; set; }
        public string Tipo { get; set; }
        public string Id_empresacliente { get; set; }
    
        public virtual Empresa_cliente Empresa_cliente { get; set; }
        public virtual ICollection<Mensaje_consulta> Mensaje_consulta { get; set; }
        public virtual ICollection<Ventas> Ventas { get; set; }
    }
}
