//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyectofinal2.Models.Menajes_db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ventas
    {
        public Ventas()
        {
            this.Carrito = new HashSet<Carrito>();
            this.Despacho = new HashSet<Despacho>();
        }
    
        public int Id_ventas { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> Total { get; set; }
        public string Rut { get; set; }
    
        public virtual ICollection<Carrito> Carrito { get; set; }
        public virtual ICollection<Despacho> Despacho { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
